repos:
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length", "88", "--target-version", "py38"]  # Keep line length consistent

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: .py  # Specify the files or directories to lint, '.' represents the current directory
        args: ["--ignore=E501,E203,E501,C901, W503", "--max-line-length", "88"]  # Keep line length consistent

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--line-length", "88", "--profile", "black"]  # Keep line length consistent